import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <div className="h-screen ">
      <Head>
        <title>blog.obradovic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <div className="container mx-auto mt-32 ">
        <div className="flex flex-col-reverse  mx-auto items-center justify-evenly lg:flex-row">
          <p className="text-center text-4xl font-semibold lg:text-5xl lg:w-1/2 xl:text-6xl xl:leading-[4.3rem] lg:text-left">
            a{" "}
            <span className="underline text-decoration-8 decoration-emerald-500">
              place for my thoughts
            </span>{" "}
            about web development, reading and videogames
          </p>
          <Image
            src="/images/Z-but2.png"
            width={1000}
            height={1000}
            className="h-[500px] w-[500px] "
          />
        </div>
      </div>
    </div>
  );
}
